name: Frontend / Package Release

on:
    push:
        branches:
            - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    release:
        name: Release
        runs-on: ubuntu-20.04

        strategy:
            matrix:
                node-version: [18]

        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3

            - uses: pnpm/action-setup@v2
              with:
                  version: 7

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install

            - name: Checking for changesets
              run: pnpm changeset status --since=main

            - name: Creating `.npmrc`
              run: |
                  cat << EOF > "$HOME/.npmrc"
                    //registry.npmjs.org/:_authToken=$NPM_TOKEN
                  EOF
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Creating release pull-request or publishing
              uses: changesets/action@v1
              with:
                  title: 'chore: package release(s)'
                  commit: 'chore: package release(s)'
                  publish: pnpm run changeset:publish
                  version: pnpm run changeset:version
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
